import {
  AlertTriangle,
  Eye,
  FileText,
  FileWarning,
  GraduationCap,
  LayoutDashboard,
  Mail,
  Microscope,
  Monitor,
  Plug,
  Search,
  Shield,
  Sparkles,
  Target,
  Terminal,
  User,
} from 'lucide-react';

export const blueTeamNav = [
  { name: 'Blue Dashboard', href: 'BlueDashboard', icon: LayoutDashboard },
  { name: 'Campaigns', href: 'CampaignManager', icon: Target },
  { name: 'Playbooks', href: 'IncidentPlaybooks', icon: FileText },
  { name: 'Rules Builder', href: 'DetectionRuleBuilder', icon: AlertTriangle },
  { name: 'MITRE Matrix', href: 'MitreMatrix', icon: Target },
  { name: 'Templates', href: 'AssessmentTemplates', icon: FileText },
  { name: 'Devices', href: 'Devices', icon: Monitor },
  { name: 'Alerts', href: 'Alerts', icon: AlertTriangle },
  { name: 'Incidents', href: 'Incidents', icon: FileWarning },
  { name: 'Policies', href: 'Policies', icon: Shield },
  { name: 'Threat Intel', href: 'ThreatIntelligence', icon: Shield },
  { name: 'Advanced Scan', href: 'AdvancedScanning', icon: Shield },
  { name: 'Zero Trust', href: 'ZeroTrust', icon: Shield },
  { name: 'Honeypots', href: 'HoneypotManager', icon: Target },
  { name: 'OSINT', href: 'AttackerIntelligence', icon: Search },
  { name: 'SIEM', href: 'SIEM', icon: Shield },
  { name: 'Threat Hunt', href: 'ThreatHunting', icon: Target },
  { name: 'Sandbox', href: 'MalwareSandbox', icon: Shield },
  { name: 'Malware Zoo', href: 'MalwareZoo', icon: Microscope },
  { name: 'AI Detection', href: 'AIDetection', icon: Sparkles },
  { name: 'AI Reports', href: 'AIReports', icon: Sparkles },
  { name: 'Alert Rules', href: 'AlertRules', icon: AlertTriangle },
  { name: 'Tool Staging', href: 'ToolStaging', icon: Terminal },
  { name: 'Reports', href: 'Reports', icon: FileText },
];

export const redTeamNav = [
  { name: 'Red Dashboard', href: 'RedDashboard', icon: LayoutDashboard },
  { name: 'Campaigns', href: 'CampaignManager', icon: Target },
  { name: 'Credentials', href: 'CredentialVault', icon: Shield },
  { name: 'OPSEC Scoring', href: 'OpsecScoring', icon: Shield },
  { name: 'MITRE Matrix', href: 'MitreMatrix', icon: Target },
  { name: 'Templates', href: 'AssessmentTemplates', icon: FileText },
  { name: 'Recon Tools', href: 'ReconTools', icon: Search },
  { name: 'Breach Recon', href: 'BreachRecon', icon: Target },
  { name: 'Google Dorking', href: 'GoogleDorking', icon: Search },
  { name: 'Network Scan', href: 'NetworkScanner', icon: Search },
  { name: 'Phishing Sim', href: 'PhishingCampaigns', icon: Mail },
  { name: 'Social Eng', href: 'SocialEngineering', icon: User },
  { name: 'Attack Sims', href: 'AttackSimulations', icon: Target },
  { name: 'C2 Control', href: 'C2Dashboard', icon: Terminal },
  { name: 'Agent Builder', href: 'AgentBuilder', icon: Sparkles },
  { name: 'Payload Gen', href: 'PayloadGenerator', icon: Terminal },
  { name: 'Web Exploits', href: 'WebExploitTools', icon: Shield },
  { name: 'Password Tools', href: 'PasswordTools', icon: Shield },
  { name: 'Post-Exploit', href: 'PostExploitation', icon: Shield },
  { name: 'Encoders', href: 'EncodersDecoders', icon: Shield },
  { name: 'Reverse Eng', href: 'ReverseEngineering', icon: Shield },
  { name: 'Steganography', href: 'Steganography', icon: Eye },
  { name: 'Tool Staging', href: 'ToolStaging', icon: Terminal },
  { name: 'Reports', href: 'Reports', icon: FileText },
];

export const sharedNav = [
  { name: 'Academy', href: 'SecurityAcademy', icon: GraduationCap },
  { name: 'Integration Setup', href: 'IntegrationSetup', icon: Plug },
];
