/**
 * AI Text Detection - Uses the Seraphim LLM to analyze if text is AI-generated.
 */
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

Deno.serve(async (req) => {
  try {
    const api = createClientFromRequest(req);
    const user = await api.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    let body: { text?: string };
    try {
      body = (await req.json()) || {};
    } catch {
      return Response.json({ error: 'Invalid JSON body' }, { status: 400 });
    }

    const text = body.text?.trim();
    if (!text || text.length > 50000) {
      return Response.json(
        { error: 'text is required and must be 1-50000 characters' },
        { status: 400 }
      );
    }

    const prompt = `You are an AI detection expert. Analyze if the following text was likely generated by an AI (e.g. ChatGPT, Claude, GPT).

TEXT TO ANALYZE:
"""
${text.slice(0, 8000)}
"""

Respond with valid JSON only, no markdown:
{
  "isAI": boolean,
  "confidence": number (0-100),
  "model": string (e.g. "GPT-like", "Claude-like", "Unknown"),
  "signals": array of { "indicator": string, "explanation": string } (2-4 items)
}`;

    const aiResponse = await api.integrations.Core.InvokeLLM({
      prompt,
      response_json_schema: {
        type: 'object',
        properties: {
          isAI: { type: 'boolean' },
          confidence: { type: 'number' },
          model: { type: 'string' },
          signals: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                indicator: { type: 'string' },
                explanation: { type: 'string' },
              },
            },
          },
        },
      },
    });

    return Response.json({
      success: true,
      ...aiResponse,
      processingTime: 'LLM',
    });
  } catch (error) {
    return Response.json(
      { success: false, error: error?.message || 'Detection failed' },
      { status: 500 }
    );
  }
});
