namespace Seraphim.Engine;

internal static class KaliCatalog
{
    internal static IReadOnlyList<ToolSpec> All()
    {
        var tools = new List<ToolSpec>(400);
        AddSpecials(tools);
        KaliSpecials.Add(tools);
        Add(tools, "Information Gathering", Host, InfoGathering);
        Add(tools, "Vulnerability Analysis", Host, Vulnerability);
        Add(tools, "Web Application Analysis", Web, WebApp);
        Add(tools, "Database Assessment", Host, Database);
        Add(tools, "Password Attacks", Pass, Passwords);
        Add(tools, "Wireless Attacks", Wireless, WirelessTools);
        Add(tools, "Reverse Engineering", File, Reverse);
        Add(tools, "Exploitation Tools", Host, Exploitation);
        Add(tools, "Sniffing & Spoofing", Iface, Sniffing);
        Add(tools, "Post Exploitation", Host, PostEx);
        Add(tools, "Forensics", File, Forensics);
        Add(tools, "Reporting Tools", Url, Reporting);
        Add(tools, "Social Engineering Tools", Host, Social);
        Add(tools, "Hardware Hacking", File, Hardware);
        return tools;
    }

    private static void Add(
        List<ToolSpec> tools,
        string category,
        Func<string, string, string, string, ToolSpec> template,
        (string Id, string Exe, string Name, string Summary)[] rows)
    {
        var seen = new HashSet<string>(tools.Select(t => t.Id), StringComparer.OrdinalIgnoreCase);
        foreach (var (id, exe, name, summary) in rows)
        {
            if (!seen.Add(id)) continue;
            tools.Add(template(id, exe, name, category) with { Summary = summary });
        }
    }

    private static ToolSpec Host(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "", [Fields.Target(), Fields.Ports(), Fields.Verbose()]);

    private static ToolSpec Web(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "", [Fields.Url(), Fields.Wordlist(), Fields.Threads(), Fields.Verbose()]);

    private static ToolSpec Pass(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "",
        [
            Fields.Target("What to log into", "e.g. ssh://10.0.0.1"),
            Fields.Text("user", "Username", "-l", "admin"),
            Fields.Wordlist("-P"),
            Fields.Verbose(),
        ]);

    private static ToolSpec Wireless(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "",
        [
            Fields.Iface(),
            Fields.Text("bssid", "Router's Wi-Fi address", "-b", "00:11:22:33:44:55"),
            Fields.Text("channel", "Wi-Fi channel", "-c", "6"),
            Fields.Verbose(),
        ]);

    private static ToolSpec File(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "", [Fields.InputFile(), Fields.Verbose()]);

    private static ToolSpec Iface(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "",
        [
            Fields.Iface(),
            Fields.Text("count", "Packet count", "-c", "100"),
            Fields.Target("Computer or traffic filter", "e.g. 10.0.0.1", ""),
            Fields.Verbose(),
        ]);

    private static ToolSpec Url(string id, string exe, string name, string cat) =>
        new(id, name, cat, exe, "", [Fields.Url(), Fields.Verbose()]);

    private static void AddSpecials(List<ToolSpec> tools)
    {
        tools.Add(new ToolSpec(
            "nmap", "Nmap", "Information Gathering", "nmap",
            "Finds computers on a network and checks which doors (ports) are open.",
            [
                Fields.Target("Computer or network to check"),
                Fields.Text("ports", "Which ports", "-p", "e.g. 22, 80, 443"),
                Fields.Text("topPorts", "Only the most common ports (how many)", "--top-ports", "20"),
                Fields.Select("timing", "Speed (0 slow, 5 fastest)", "-T", "0", "1", "2", "3", "4", "5"),
                Fields.Flag("fast", "Quick scan of common ports", "-F"),
                Fields.Flag("service", "Identify what software is running", "-sV"),
                Fields.Flag("os", "Guess the operating system", "-O"),
                Fields.Flag("skipPing", "Don't wait for a ping reply", "-Pn"),
                Fields.Flag("connect", "Use a normal connection (no admin needed)", "-sT"),
                Fields.Flag("udp", "Also check UDP services", "-sU"),
                Fields.Flag("allPorts", "Check every TCP port", "-p-"),
                Fields.Text("script", "Extra checks (optional)", "--script", "default,safe"),
            ],
            [
                new("Quick", new Dictionary<string, string> { ["fast"] = "true" }),
                new("Service detect", new Dictionary<string, string> { ["service"] = "true", ["topPorts"] = "20" }),
                new("All TCP", new Dictionary<string, string> { ["connect"] = "true", ["allPorts"] = "true" }),
            ]));

        tools.Add(new ToolSpec(
            "sqlmap", "sqlmap", "Web Application Analysis", "sqlmap",
            "Checks a website form or address for SQL injection (database tricks).",
            [
                Fields.Url(),
                Fields.Text("data", "Form fields to send", "--data", "id=1"),
                Fields.Select("level", "How thorough (1–5)", "--level", "1", "2", "3", "4", "5"),
                Fields.Select("risk", "How risky (1–3)", "--risk", "1", "2", "3"),
                Fields.Flag("batch", "Don't ask questions, just run", "--batch"),
                Fields.Flag("dbs", "List databases", "--dbs"),
                Fields.Flag("osShell", "Try to open a command prompt on the server", "--os-shell"),
            ]));

        tools.Add(new ToolSpec(
            "gobuster", "Gobuster", "Web Application Analysis", "gobuster",
            "Looks for hidden pages and folders on a website.",
            [
                Fields.Url(),
                Fields.Wordlist(),
                Fields.Threads(),
                Fields.Text("extensions", "File types to try", "-x", "e.g. php, html, txt"),
                Fields.Flag("follow", "Follow send-aways (redirects)", "-r"),
            ],
            Prefix: ["dir"]));

        tools.Add(new ToolSpec(
            "hydra", "Hydra", "Password Attacks", "hydra",
            "Tries usernames and passwords against a login.",
            [
                Fields.Target("What to log into", "e.g. ssh://10.0.0.1"),
                Fields.Text("user", "Username", "-l", "admin"),
                Fields.Wordlist("-P"),
                Fields.Threads("-t"),
                Fields.Flag("verbose", "Show extra detail", "-V"),
            ]));

        tools.Add(new ToolSpec(
            "recon", "Recon (built-in)", "Information Gathering", "recon",
            "Looks up a name on the internet (DNS). Built in. Nothing extra to install.",
            [Fields.Target("Name to look up", "lab.local", "lab.local")],
            Presets: [new("DNS", new Dictionary<string, string>())],
            BuiltIn: true));

        tools.Add(new ToolSpec(
            "hibp", "Have I Been Pwned", "Password Attacks", "hibp",
            "Checks whether a password showed up in known leaks. The full password stays on this PC.",
            [
                new("prefix", "First 5 characters of the password hash", FieldKind.Text, "", Required: true, Placeholder: "e.g. 21BD1"),
            ],
            Presets: [new("Hash prefix", new Dictionary<string, string>())],
            BuiltIn: true));
    }

    private static readonly (string Id, string Exe, string Name, string Summary)[] InfoGathering =
    [
        ("0trace", "0trace.sh", "0trace", "Hop-limited traceroute that evades some firewalls."),
        ("arping", "arping", "arping", "ARP ping a host on the local segment."),
        ("arp-scan", "arp-scan", "arp-scan", "Layer-2 host discovery via ARP."),
        ("braa", "braa", "braa", "Mass SNMP scanner."),
        ("dmitry", "dmitry", "DMitry", "Deepmagic Information Gathering Tool."),
        ("dnsenum", "dnsenum", "dnsenum", "DNS enumeration and zone transfer attempts."),
        ("dnsmap", "dnsmap", "dnsmap", "Subdomain brute force."),
        ("dnsrecon", "dnsrecon", "dnsrecon", "DNS enumeration, zone walk, cache snoop."),
        ("dnstracer", "dnstracer", "dnstracer", "Trace DNS delegation path."),
        ("dnswalk", "dnswalk", "dnswalk", "DNS zone debugger."),
        ("enum4linux", "enum4linux", "enum4linux", "SMB/NetBIOS enumeration (Samba wrapper)."),
        ("enum4linux-ng", "enum4linux-ng", "enum4linux-ng", "Next-gen SMB enumeration."),
        ("fierce", "fierce", "fierce", "DNS reconnaissance and adjacent-range scan."),
        ("firewalk", "firewalk", "Firewalk", "ACL mapping via TTL-expired packets."),
        ("fping", "fping", "fping", "Fast parallel ICMP ping."),
        ("fragrouter", "fragrouter", "fragrouter", "NIDS evasion via fragmenting."),
        ("ftester", "ftest", "FTester", "Firewall / IDS tester."),
        ("hping3", "hping3", "hping3", "Craft TCP/UDP/ICMP packets."),
        ("ike-scan", "ike-scan", "ike-scan", "Discover and fingerprint IKE/IPsec VPNs."),
        ("intrace", "intrace", "intrace", "Hop traceroute using existing TCP connections."),
        ("irpas", "ass", "IRPAS", "Internetwork Routing Protocol Attack Suite."),
        ("lbd", "lbd", "lbd", "Detect HTTP/DNS load balancing."),
        ("legion", "legion", "LEGION", "Semi-automated network pentest GUI."),
        ("maltego", "maltego", "Maltego", "Link-analysis OSINT (launches Maltego)."),
        ("masscan", "masscan", "masscan", "Asynchronous Internet-scale port scanner."),
        ("metagoofil", "metagoofil", "metagoofil", "Extract metadata from public documents."),
        ("nbtscan", "nbtscan", "nbtscan", "NetBIOS name scanner."),
        ("ncat", "ncat", "Ncat", "Nmap's netcat with SSL and proxies."),
        ("netdiscover", "netdiscover", "netdiscover", "Active/passive ARP reconnaissance."),
        ("netmask", "netmask", "netmask", "Determine inetmask for a range."),
        ("onesixtyone", "onesixtyone", "onesixtyone", "Fast SNMP community scanner."),
        ("p0f", "p0f", "p0f", "Passive OS fingerprinting."),
        ("qsslcaudit", "qsslcaudit", "qsslcaudit", "SSL/TLS server audit."),
        ("recon-ng", "recon-ng", "Recon-ng", "Modular web reconnaissance framework."),
        ("smbmap", "smbmap", "smbmap", "Enumerate Samba share permissions."),
        ("smtp-user-enum", "smtp-user-enum", "smtp-user-enum", "VRFY/EXPN/RCPT user enum."),
        ("snmpcheck", "snmp-check", "snmp-check", "Enumerate SNMP for OS and shares."),
        ("ssldump", "ssldump", "ssldump", "SSLv3/TLS network protocol analyzer."),
        ("sslh", "sslh", "sslh", "Applicative SSL/SSH multiplexer."),
        ("sslscan", "sslscan", "sslscan", "Query SSL/TLS ciphers and certs."),
        ("sslyze", "sslyze", "SSLyze", "Fast SSL/TLS configuration scanner."),
        ("swaks", "swaks", "swaks", "Swiss Army Knife for SMTP."),
        ("thc-ipv6", "alive6", "THC-IPv6", "IPv6 attack toolkit (alive6 and friends)."),
        ("theharvester", "theHarvester", "theHarvester", "OSINT emails, names, subdomains."),
        ("tlssled", "tlssled", "TLSSLed", "SSL/TLS evaluation script."),
        ("twofi", "twofi", "twofi", "Twitter words of interest for wordlists."),
        ("unicornscan", "unicornscan", "Unicornscan", "Asynchronous stimulus scanner."),
        ("urlcrazy", "urlcrazy", "urlcrazy", "Generate and test domain typos."),
        ("wafw00f", "wafw00f", "Wafw00f", "Identify web application firewalls."),
        ("zenmap", "zenmap", "Zenmap", "Official Nmap GUI."),
        ("whois", "whois", "whois", "Query WHOIS registrars."),
        ("traceroute", "traceroute", "traceroute", "IP path trace."),
        ("amass", "amass", "Amass", "In-depth DNS and surface mapping."),
        ("subfinder", "subfinder", "subfinder", "Passive subdomain discovery."),
        ("assetfinder", "assetfinder", "assetfinder", "Find domains and subdomains related to a name."),
        ("spiderfoot", "spiderfoot", "SpiderFoot", "Automated OSINT / attack-surface scan."),
        ("naabu", "naabu", "naabu", "Fast port scanner (ProjectDiscovery)."),
        ("dnsx", "dnsx", "dnsx", "DNS toolkit for records and resolvers."),
        ("sublist3r", "sublist3r", "Sublist3r", "Enumerate subdomains across search engines."),
        ("finalrecon", "finalrecon", "FinalRecon", "All-in-one web reconnaissance."),
        ("reconspider", "reconspider", "ReconSpider", "OSINT plus scan automation."),
        ("sherlock", "sherlock", "Sherlock", "Hunt usernames across social sites."),
        ("hosthunter", "hosthunter", "HostHunter", "Recon hostnames from IP ranges."),
        ("bing-ip2hosts", "bing-ip2hosts", "bing-ip2hosts", "Enumerate hostnames via Bing."),
        ("cloud-enum", "cloud-enum", "cloud-enum", "Multi-cloud OSINT (Azure/AWS/GCP)."),
        ("osrframework", "osrf", "OSRFramework", "Username / domain OSINT suite."),
        ("maryam", "maryam", "Maryam", "OSINT framework."),
        ("photon", "photon", "Photon", "Fast crawler for OSINT."),
        ("sn0int", "sn0int", "sn0int", "Semi-automatic OSINT framework."),
        ("emailharvester", "emailharvester", "EmailHarvester", "Harvest emails from search engines."),
        ("netexec", "nxc", "NetExec", "Windows/AD situational awareness (CME successor)."),
        ("httpx-toolkit", "httpx-toolkit", "httpx-toolkit", "Probe HTTP hosts (ProjectDiscovery)."),
        ("findomain", "findomain", "findomain", "Fast subdomain enumerator."),
        ("massdns", "massdns", "massdns", "High-performance DNS stub resolver."),
        ("altdns", "altdns", "altdns", "Permutation-based subdomain discovery."),
        ("dnsgen", "dnsgen", "dnsgen", "Generate DNS name permutations."),
        ("dnstwist", "dnstwist", "dnstwist", "Lookalike domain discovery."),
        ("certgraph", "certgraph", "certgraph", "Crawl CT logs for related domains."),
        ("ident-user-enum", "ident-user-enum", "ident-user-enum", "Ident protocol username enumeration."),
        ("goofile", "goofile", "goofile", "Search Google for file types on a domain."),
        ("knocker", "knocker", "knocker", "Simple TCP port knocker / scanner."),
        ("nmapsi4", "nmapsi4", "NmapSI4", "Qt frontend for Nmap."),
        ("nbtscan-unixwiz", "nbtscan-unixwiz", "nbtscan-unixwiz", "NetBIOS scanner (unixwiz fork)."),
        ("snmpenum", "snmpenum", "snmpenum", "SNMP enumeration script."),
        ("amap", "amap", "Amap", "Application mapper (protocol detect)."),
        ("autorecon", "autorecon", "AutoRecon", "Multi-threaded target reconnaissance."),
        ("ivre", "ivre", "IVRE", "Network recon framework."),
        ("tookie-osint", "tookie-osint", "Tookie OSINT", "OSINT username and account hunt."),
        ("mxcheck", "mxcheck", "mxcheck", "Mail-exchanger reconnaissance."),
        ("whatmask", "whatmask", "whatmask", "Subnet and wildcard calculator."),
        ("nextnet", "nextnet", "nextnet", "Discovery scanner."),
        ("netscanner", "netscanner", "netscanner", "Network scanner TUI."),
        ("dscan", "dscan", "dscan", "Distributed / fast scanner."),
        ("pnscan", "pnscan", "pnscan", "Parallel network scanner."),
        ("cloudbrute", "cloudbrute", "CloudBrute", "Cloud-resource enumeration."),
        ("s3scanner", "s3scanner", "S3Scanner", "Find open S3 buckets."),
        ("pacu", "pacu", "Pacu", "AWS exploitation framework (recon modules)."),
        ("azurehound", "azurehound", "AzureHound", "Azure AD / Entra attack-path collector."),
        ("ldapdomaindump", "ldapdomaindump", "ldapdomaindump", "Dump Active Directory via LDAP."),
        ("rustscan", "rustscan", "RustScan", "Fast port scanner that pipes to Nmap."),
        ("nping", "nping", "Nping", "Nmap packet generator and pinger."),
        ("host", "host", "host", "DNS lookup (bind9-host)."),
        ("dig", "dig", "dig", "DNS lookup (bind9-dnsutils)."),
        ("ldapsearch", "ldapsearch", "ldapsearch", "LDAP search (OpenLDAP)."),
        ("smbclient", "smbclient", "smbclient", "SMB/CIFS client."),
        ("rpcclient", "rpcclient", "rpcclient", "MS-RPC client (Samba)."),
        ("snmpwalk", "snmpwalk", "snmpwalk", "SNMP tree walk."),
        ("nmblookup", "nmblookup", "nmblookup", "NetBIOS name query."),
        ("bloodhound-python", "bloodhound-python", "BloodHound.py", "BloodHound Python ingestor."),
        ("crackmapexec", "crackmapexec", "CrackMapExec", "Legacy CME (NetExec predecessor)."),
        ("kerbrute", "kerbrute", "kerbrute", "Kerberos user enum and spray."),
        ("impacket-GetNPUsers", "impacket-GetNPUsers", "impacket GetNPUsers", "Find AS-REP roastable users."),
        ("impacket-GetUserSPNs", "impacket-GetUserSPNs", "impacket GetUserSPNs", "Find Kerberoastable SPNs."),
        ("impacket-lookupsid", "impacket-lookupsid", "impacket lookupsid", "SID brute force via LSA."),
        ("tlsx", "tlsx", "tlsx", "TLS handshake and certificate grabber."),
        ("ace-voip", "ace", "ACE", "Automated Corporate Enumerator (VoIP)."),
        ("fragroute", "fragroute", "fragroute", "Intercept and fragment outbound traffic."),
        ("shuffledns", "shuffledns", "shuffledns", "Mass DNS resolver with wildcard handling."),
        ("alterx", "alterx", "alterx", "Subdomain permutation wordlist generator."),
        ("asnmap", "asnmap", "asnmap", "Map IPs and domains to ASNs."),
        ("uncover", "uncover", "uncover", "Discover hosts from search engines / APIs."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Vulnerability =
    [
        ("nikto", "nikto", "Nikto", "Web server scanner for dangerous files and outdated software."),
        ("nuclei", "nuclei", "Nuclei", "Template-based vulnerability scanner."),
        ("lynis", "lynis", "Lynis", "Host hardening and audit scanner."),
        ("gvm", "gvm-cli", "GVM / OpenVAS", "Greenbone Vulnerability Management."),
        ("bed", "bed", "BED", "Bruteforce Exploit Detector — protocol fuzzing."),
        ("cisco-auditing-tool", "CAT", "Cisco Auditing Tool", "Scan Cisco routers for common issues."),
        ("cisco-global-exploiter", "cge", "Cisco Global Exploiter", "Cisco device exploitation toolkit."),
        ("cisco-ocs", "cisco-ocs", "cisco-ocs", "Cisco scanner."),
        ("cisco-torch", "cisco-torch", "cisco-torch", "Mass Cisco scanner (telnet/ssh/snmp/tftp)."),
        ("copy-router-config", "copy-router-config.pl", "copy-router-config", "Copy Cisco configs via SNMP."),
        ("dhcpig", "dhcpig", "DHCPig", "DHCP exhaustion stress test."),
        ("enumiax", "enumiax", "enumIAX", "Enumerate Inter-Asterisk eXchange users."),
        ("ohrwurm", "ohrwurm", "ohrwurm", "RTP fuzzing for VoIP."),
        ("peass", "linpeas.sh", "PEASS", "Privilege-escalation suite (linPEAS/winPEAS)."),
        ("protos-sip", "protos-sip", "PROTOS SIP", "SIP protocol test suite."),
        ("rtpbreak", "rtpbreak", "rtpbreak", "Detect, reconstruct, and analyze RTP sessions."),
        ("rtpflood", "rtpflood", "rtpflood", "RTP flood utility."),
        ("rtpinsertsound", "rtpinsertsound", "rtpinsertsound", "Insert audio into an RTP stream."),
        ("rtpmixsound", "rtpmixsound", "rtpmixsound", "Mix audio into an RTP stream."),
        ("sctpscan", "sctpscan", "SCTPScan", "SCTP association scanner."),
        ("sfuzz", "sfuzz", "sfuzz", "Simple protocol fuzzer."),
        ("siege", "siege", "Siege", "HTTP load tester / regression."),
        ("siparmyknife", "siparmyknife", "SIP Army Knife", "SIP packet fuzzer."),
        ("sipp", "sipp", "SIPp", "SIP traffic generator."),
        ("sipsak", "sipsak", "sipsak", "SIP Swiss-army knife."),
        ("sipvicious", "svmap", "SIPVicious", "SIP PBX scanner suite (svmap)."),
        ("slowhttptest", "slowhttptest", "slowhttptest", "Slow HTTP DoS tester."),
        ("spike", "generic_send_tcp", "SPIKE", "Fuzzing framework (generic_send_tcp)."),
        ("t50", "t50", "T50", "Multi-protocol packet injector."),
        ("thc-ssl-dos", "thc-ssl-dos", "THC-SSL-DOS", "SSL renegotiation stress test."),
        ("unix-privesc-check", "unix-privesc-check", "unix-privesc-check", "Find local privilege-escalation vectors."),
        ("voiphopper", "voiphopper", "voiphopper", "VLAN hopping for VoIP phones."),
        ("yersinia", "yersinia", "Yersinia", "Layer-2 attack framework."),
        ("aflpp", "afl-fuzz", "AFL++", "American Fuzzy Lop plus plus."),
        ("wfuzz", "wfuzz", "Wfuzz", "Web application fuzzer."),
        ("iaxflood", "iaxflood", "iaxflood", "IAX protocol flooder."),
        ("inviteflood", "inviteflood", "inviteflood", "SIP INVITE flooder."),
        ("trivy", "trivy", "Trivy", "Container and filesystem CVE scanner."),
        ("testssl", "testssl.sh", "testssl.sh", "TLS/SSL cipher and vulnerability check."),
        ("wapiti", "wapiti", "Wapiti", "Black-box web vulnerability scanner."),
        ("legion-vuln", "legion", "LEGION (vuln)", "Automated scanner GUI (same binary as info-gathering)."),
        ("nipper-ng", "nipper", "nipper-ng", "Audit network device configs."),
        ("tiger", "tiger", "Tiger", "UNIX security audit."),
        ("doona", "doona", "Doona", "BED fork — protocol fuzzer."),
        ("changeme", "changeme", "changeme", "Default-credential scanner."),
        ("sploitscan", "sploitscan", "SploitScan", "Map CVEs to public exploits."),
        ("goldeneye", "goldeneye", "GoldenEye", "HTTP DoS tester."),
        ("gitleaks", "gitleaks", "Gitleaks", "Hunt secrets in git repos."),
        ("trufflehog", "trufflehog", "TruffleHog", "Find leaked credentials in repos."),
        ("syft", "syft", "Syft", "SBOM generator for images and filesystems."),
        ("snort", "snort", "Snort", "Network intrusion detection / packet logger."),
        ("sentrypeer", "sentrypeer", "SentryPeer", "SIP honeypot and threat intel."),
        ("sara", "sara", "SARA", "Security Auditor's Research Assistant."),
        ("patchleaks", "patchleaks", "PatchLeaks", "Map patches to leaked details."),
        ("dumpsterdiver", "dumpsterdiver", "DumpsterDiver", "Hunt secrets in filesystems."),
        ("passdetective", "passdetective", "PassDetective", "Detect passwords in data."),
        ("gitxray", "gitxray", "Gitxray", "Git repository security analysis."),
        ("sippts", "sippts", "SIPPTS", "SIP penetration-testing suite."),
        ("libfindrtp", "findrtp", "libfindrtp", "Locate RTP streams for VoIP analysis."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] WebApp =
    [
        ("burpsuite", "burpsuite", "Burp Suite", "Intercepting HTTP(S) proxy (launches Burp)."),
        ("zaproxy", "zap.sh", "OWASP ZAP", "Zed Attack Proxy."),
        ("commix", "commix", "Commix", "Command-injection exploitation."),
        ("dirb", "dirb", "dirb", "Web content scanner with wordlists."),
        ("dirbuster", "dirbuster", "DirBuster", "Multi-threaded directory brute force GUI."),
        ("ffuf", "ffuf", "ffuf", "Fast web fuzzer (Go)."),
        ("feroxbuster", "feroxbuster", "feroxbuster", "Recursive content discovery."),
        ("dirsearch", "dirsearch", "dirsearch", "Path brute force for web servers."),
        ("wpscan", "wpscan", "WPScan", "WordPress vulnerability scanner."),
        ("joomscan", "joomscan", "JoomScan", "Joomla scanner."),
        ("whatweb", "whatweb", "WhatWeb", "Identify CMS, JavaScript, and plugins."),
        ("skipfish", "skipfish", "Skipfish", "Active web reconnaissance crawler."),
        ("uniscan", "uniscan", "Uniscan", "LFI/RFI/RSS remote file scanner."),
        ("xsser", "xsser", "XSSer", "Automatic XSS detection and exploitation."),
        ("xsstrike", "xsstrike", "XSStrike", "XSS detection with context analysis."),
        ("xsrfprobe", "xsrfprobe", "XSRFProbe", "CSRF audit and exploit."),
        ("cadaver", "cadaver", "cadaver", "WebDAV command-line client."),
        ("davtest", "davtest", "DAVTest", "Exploit WebDAV upload."),
        ("dotdotpwn", "dotdotpwn", "DotDotPwn", "Directory traversal fuzzer."),
        ("hakrawler", "hakrawler", "hakrawler", "Fast web crawler for endpoints."),
        ("gospider", "gospider", "gospider", "Fast Go spider / crawler."),
        ("httrack", "httrack", "HTTrack", "Website copier / mirror."),
        ("httprint", "httprint", "httprint", "Web server fingerprinting."),
        ("heartleech", "heartleech", "heartleech", "Heartbleed memory leech."),
        ("jboss-autopwn", "jboss-autopwn", "JBoss-Autopwn", "JBoss deployment and shell."),
        ("jsql-injection", "jsql", "jSQL Injection", "Java GUI for SQL injection."),
        ("padbuster", "padbuster", "PadBuster", "Padding-oracle attack tool."),
        ("paros", "paros", "Paros", "HTTP/HTTPS proxy for assessing web apps."),
        ("watobo", "watobo", "WATOBO", "Intercepting proxy with scanners."),
        ("webscarab", "webscarab", "WebScarab", "OWASP intercepting proxy (legacy)."),
        ("weevely", "weevely", "Weevely", "Weaponized web shell."),
        ("apache-users", "apache-users", "apache-users", "Enumerate Apache userdirs."),
        ("arjun", "arjun", "Arjun", "HTTP parameter discovery."),
        ("cmseek", "cmseek", "CMSeeK", "CMS detection and exploitation."),
        ("sstimap", "sstimap", "SSTImap", "Server-side template injection."),
        ("parsero", "parsero", "Parsero", "Read and test robots.txt."),
        ("wig", "wig", "WIG", "WebApp Information Gatherer."),
        ("caido", "caido", "Caido", "Modern web-security auditing proxy."),
        ("caido-cli", "caido-cli", "Caido CLI", "Caido from the command line."),
        ("owasp-mantra-ff", "mantra", "OWASP Mantra", "Firefox-based web testing browser."),
        ("web-cache-vulnerability-scanner", "wcvs", "Web Cache Vulnerability Scanner", "Detect web-cache poisoning."),
        ("phpggc", "phpggc", "PHPGGC", "PHP gadget-chain generator."),
        ("tinja", "tinja", "Tinja", "Template injection scanner."),
        ("wpprobe", "wpprobe", "WPProbe", "WordPress probing."),
        ("crlfuzz", "crlfuzz", "CRLfuzz", "CRLF injection fuzzer."),
        ("getallurls", "gau", "gau", "Fetch known URLs from AlienVault/Wayback/Common Crawl."),
        ("waybackpy", "waybackpy", "waybackpy", "Wayback Machine CLI."),
        ("uro", "uro", "uro", "Declutter URL lists."),
        ("httprobe", "httprobe", "httprobe", "Take hosts, return live HTTP(S)."),
        ("colly", "colly", "Colly", "Go scraping / crawling."),
        ("humble", "humble", "humble", "HTTP header and hardening checker."),
        ("hurl", "hurl", "Hurl", "Run HTTP requests from plain text."),
        ("katana", "katana", "Katana", "Next-gen web crawler."),
        ("dalfox", "dalfox", "Dalfox", "XSS scanner and parameter analyzer."),
        ("paramspider", "paramspider", "ParamSpider", "Mine parameters from web archives."),
        ("waybackurls", "waybackurls", "waybackurls", "Fetch URLs from the Wayback Machine."),
        ("aquatone", "aquatone", "Aquatone", "Visual inspection of websites across hosts."),
        ("interactsh-client", "interactsh-client", "interactsh-client", "OOB interaction client (ProjectDiscovery)."),
        ("jwt-tool", "jwt_tool", "jwt_tool", "JWT attack toolkit."),
        ("wig-ng", "wig-ng", "WIG-ng", "WebApp Information Gatherer (next-gen)."),
        ("robotstxt", "robotstxt", "robotstxt", "Fetch and parse robots.txt."),
        ("subjack", "subjack", "subjack", "Subdomain takeover checker."),
        ("redsocks", "redsocks", "redsocks", "Transparent TCP-to-proxy redirector."),
        ("tplmap", "tplmap", "Tplmap", "Server-side template injection (legacy)."),
        ("ysoserial", "ysoserial", "ysoserial", "Java deserialization gadget payloads."),
        ("graphqlmap", "graphqlmap", "GraphQLmap", "GraphQL injection and enumeration."),
        ("phpsploit", "phpsploit", "phpSploit", "Stealth post-exploitation web framework."),
        ("htshells", "htshells", "htshells", "Self-contained .htaccess web shells."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Database =
    [
        ("oscanner", "oscanner", "Oscanner", "Oracle assessment."),
        ("sidguesser", "sidguess", "SIDGuesser", "Guess Oracle SIDs."),
        ("sqldict", "sqldict", "SQLdict", "Dictionary attack against SQL servers."),
        ("sqlitebrowser", "sqlitebrowser", "DB Browser for SQLite", "Inspect SQLite databases."),
        ("sqlninja", "sqlninja", "sqlninja", "SQL Server injection and takeover."),
        ("sqlsus", "sqlsus", "sqlsus", "MySQL injection and takeover."),
        ("tnscmd10g", "tnscmd10g", "tnscmd10g", "Oracle TNS listener poke."),
        ("mdbtools", "mdb-tables", "mdbtools", "Read Microsoft Access databases."),
        ("odat", "odat", "ODAT", "Oracle Database Attacking Tool."),
        ("mssqlpwner", "mssqlpwner", "MSSQLpwner", "MSSQL abuse and lateral movement."),
        ("sqlmc", "sqlmc", "sqlmc", "SQL injection mass checker."),
        ("mongo-tools", "mongosh", "MongoDB tools", "mongo shell / dump / restore."),
        ("dbeaver", "dbeaver", "DBeaver", "Universal database GUI client."),
        ("mysql", "mysql", "MySQL client", "MariaDB/MySQL command-line client."),
        ("psql", "psql", "psql", "PostgreSQL interactive terminal."),
        ("redis-cli", "redis-cli", "redis-cli", "Redis command-line interface."),
        ("sqsh", "sqsh", "sqsh", "Sybase and Microsoft SQL command-line client."),
        ("impacket-mssqlclient", "impacket-mssqlclient", "impacket mssqlclient", "MSSQL client with NTLM and Kerberos."),
        ("impacket-mysqlclient", "impacket-mysqlclient", "impacket mysqlclient", "MySQL client from Impacket."),
        ("mongodump", "mongodump", "mongodump", "MongoDB backup utility."),
        ("mongorestore", "mongorestore", "mongorestore", "MongoDB restore utility."),
        ("isql", "isql", "isql", "unixODBC interactive SQL shell."),
        ("jsql-db", "jsql", "jSQL (database)", "Java GUI for SQL injection against DB targets."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Passwords =
    [
        ("john", "john", "John the Ripper", "Offline password cracker."),
        ("hashcat", "hashcat", "hashcat", "GPU password recovery."),
        ("hashcat-utils", "combinator.bin", "hashcat-utils", "Wordlist combinator and friends."),
        ("medusa", "medusa", "Medusa", "Parallel network login brute force."),
        ("ncrack", "ncrack", "Ncrack", "High-speed network auth cracking."),
        ("patator", "patator", "Patator", "Multi-purpose brute forcer."),
        ("cewl", "cewl", "CeWL", "Spider a site to build a wordlist."),
        ("crunch", "crunch", "crunch", "Generate custom wordlists."),
        ("hash-identifier", "hash-identifier", "hash-identifier", "Identify hash types."),
        ("hashid", "hashid", "hashID", "Identify hashes from their format."),
        ("chntpw", "chntpw", "chntpw", "Blank or change Windows SAM passwords."),
        ("cmospwd", "cmospwd", "cmospwd", "Decrypt CMOS/BIOS passwords."),
        ("fcrackzip", "fcrackzip", "fcrackzip", "Zip password cracker."),
        ("gpp-decrypt", "gpp-decrypt", "gpp-decrypt", "Decrypt GPP cpassword."),
        ("maskprocessor", "maskprocessor", "maskprocessor", "High-performance mask engine for hashcat."),
        ("ophcrack", "ophcrack", "ophcrack", "Windows LM/NTCR rainbow tables."),
        ("pack", "policygen", "PACK", "Password Analysis and Cracking Kit."),
        ("pack2", "pack2", "PACK2", "Updated PACK utilities."),
        ("pdfcrack", "pdfcrack", "pdfcrack", "PDF password recovery."),
        ("pipal", "pipal", "pipal", "Password list analysis."),
        ("polenum", "polenum", "polenum", "Enumerate password policy via RPC."),
        ("rainbowcrack", "rcrack", "RainbowCrack", "Rainbow-table cracker."),
        ("rarcrack", "rarcrack", "rarcrack", "RAR/ZIP/7z brute force."),
        ("rcracki-mt", "rcracki_mt", "rcracki-mt", "Multithreaded rainbow crack."),
        ("rsmangler", "rsmangler", "RSMangler", "Mangle words into password candidates."),
        ("samdump2", "samdump2", "samdump2", "Dump Windows SAM hashes."),
        ("sipcrack", "sipcrack", "sipcrack", "SIP digest cracker."),
        ("statsprocessor", "statsprocessor", "statsprocessor", "Markov-style word generator."),
        ("sucrack", "sucrack", "sucrack", "Crack local su passwords via wordlist."),
        ("thc-pptp-bruter", "thc-pptp-bruter", "THC-PPTP-bruter", "PPTP brute force."),
        ("truecrack", "truecrack", "truecrack", "TrueCrypt volume cracker."),
        ("xfreerdp", "xfreerdp", "xfreerdp", "FreeRDP client (password spraying helper)."),
        ("crackle", "crackle", "crackle", "Crack BLE encryption."),
        ("name-that-hash", "nth", "Name-That-Hash", "Identify a hash and suggest tools."),
        ("princeprocessor", "pp64", "princeprocessor", "PRINCE wordlist generator."),
        ("seclists", "seclists", "Seclists", "Wordlist collection. Install the seclists package; this entry does not spawn a shell."),
        ("crowbar", "crowbar", "Crowbar", "Brute force RDP/VNC/SSH keys."),
        ("brutespray", "brutespray", "BruteSpray", "Brute default creds from nmap output."),
        ("bopscrk", "bopscrk", "bopscrk", "Password-pattern wordlist generator."),
        ("legba", "legba", "legba", "Multiprotocol credentials brute forcer."),
        ("multiforcer", "multiforcer", "Multiforcer", "GPU hash cracker."),
        ("wordlistraider", "wordlistraider", "WordlistRaider", "Mutate and raid wordlists."),
        ("creddump7", "creddump7", "creddump7", "Extract Windows credentials from dumps."),
        ("johnny", "johnny", "Johnny", "GUI for John the Ripper."),
        ("hydra-gtk", "xhydra", "xHydra", "Hydra GTK front-end."),
        ("ophcrack-cli", "ophcrack-cli", "ophcrack-cli", "ophcrack without the GUI."),
        ("pth-smbclient", "pth-smbclient", "pth-smbclient", "Pass-the-hash SMB client."),
        ("pth-winexe", "pth-winexe", "pth-winexe", "Pass-the-hash remote exec."),
        ("bruteforce-luks", "bruteforce-luks", "bruteforce-luks", "LUKS volume brute force."),
        ("bruteforce-salted-openssl", "bruteforce-salted-openssl", "bruteforce-salted-openssl", "OpenSSL salted-file brute force."),
        ("bruteforce-wallet", "bruteforce-wallet", "bruteforce-wallet", "Cryptocurrency wallet brute force."),
        ("cisco7crack", "cisco7crack", "cisco7crack", "Decrypt Cisco type-7 passwords."),
        ("h8mail", "h8mail", "h8mail", "Email OSINT and breach lookup."),
        ("spray", "spray", "spray", "Password spraying helper."),
        ("spraykatz", "spraykatz", "Spraykatz", "Remote hash dump via spray."),
        ("atomizer", "atomizer", "Atomizer", "SprayingToolkit password spray."),
        ("rling", "rling", "rling", "Fast wordlist deduplicator."),
        ("crack", "crack", "Crack", "Password cracker (crack package)."),
        ("freerdp3", "xfreerdp", "FreeRDP 3", "RDP client (freerdp3-x11)."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] WirelessTools =
    [
        ("aircrack-ng", "aircrack-ng", "Aircrack-ng", "WEP/WPA crack plus capture suite."),
        ("airgeddon", "airgeddon", "airgeddon", "Multi-use bash wireless auditor."),
        ("asleap", "asleap", "asleap", "Cisco LEAP / PPTP challenge crack."),
        ("bully", "bully", "bully", "WPS brute force (reaver-class)."),
        ("cowpatty", "cowpatty", "coWPAtty", "WPA-PSK dictionary attack."),
        ("eapmd5pass", "eapmd5pass", "eapmd5pass", "EAP-MD5 offline crack."),
        ("fern-wifi-cracker", "fern-wifi-cracker", "Fern WiFi Cracker", "GUI wireless auditor."),
        ("freeradius-wpe", "radiusd", "FreeRADIUS-WPE", "Rogue RADIUS for EAP creds."),
        ("hostapd-wpe", "hostapd-wpe", "hostapd-wpe", "Rogue AP for 802.1X creds."),
        ("iw", "iw", "iw", "nl80211 wireless configuration."),
        ("kismet", "kismet", "Kismet", "Wireless sniffer and IDS."),
        ("macchanger", "macchanger", "macchanger", "Spoof a MAC address."),
        ("mdk3", "mdk3", "mdk3", "802.11 stress-test toolkit."),
        ("mdk4", "mdk4", "mdk4", "Successor to mdk3."),
        ("pixiewps", "pixiewps", "pixiewps", "Offline WPS PIN attack."),
        ("reaver", "reaver", "Reaver", "WPS PIN brute force."),
        ("wifi-honey", "wifi-honey", "wifi-honey", "Fake-AP honey pot."),
        ("wifite", "wifite", "Wifite", "Automated wireless auditor."),
        ("hcxtools", "hcxdumptool", "hcxtools", "Capture and convert PMKID/EAPOL."),
        ("eaphammer", "eaphammer", "EAPHammer", "Hostile portal / evil twin."),
        ("fluxion", "fluxion", "Fluxion", "Social-engineering WPA handshake."),
        ("wifiphisher", "wifiphisher", "Wifiphisher", "Rogue-AP phishing."),
        ("wifipumpkin3", "wifipumpkin3", "WiFi-Pumpkin3", "Rogue AP framework."),
        ("sparrow-wifi", "sparrow-wifi", "Sparrow-WiFi", "GUI spectrum analyzer."),
        ("horst", "horst", "horst", "Lightweight 802.11 scanner."),
        ("blue-hydra", "blue_hydra", "Blue Hydra", "Bluetooth device discovery."),
        ("bluelog", "bluelog", "Bluelog", "Bluetooth site survey."),
        ("blueranger", "blueranger", "BlueRanger", "Estimate Bluetooth distance."),
        ("bluesnarfer", "bluesnarfer", "bluesnarfer", "Bluesnarf a device."),
        ("bluez", "bluetoothctl", "BlueZ", "Linux Bluetooth stack CLI."),
        ("bluez-hcidump", "hcidump", "hcidump", "HCI sniffer."),
        ("btscanner", "btscanner", "btscanner", "Bluetooth device enumerator."),
        ("redfang", "fang", "RedFang", "Find hidden Bluetooth devices."),
        ("spooftooph", "spooftooph", "Spooftooph", "Spoof and clone Bluetooth."),
        ("ubertooth", "ubertooth-util", "Ubertooth", "BLE/Classic sniffing hardware CLI."),
        ("gnuradio", "gnuradio-companion", "GNU Radio", "SDR flowgraph companion."),
        ("proxmark3", "pm3", "Proxmark3", "RFID/NFC research (Proxmark)."),
        ("rfdump", "rfdump", "RFDump", "Detect RFID tags."),
        ("chirp", "chirp", "CHIRP", "Radio programming."),
        ("gqrx-sdr", "gqrx", "GQRX", "SDR receiver GUI."),
        ("hackrf", "hackrf_info", "HackRF", "HackRF One utilities."),
        ("inspectrum", "inspectrum", "inspectrum", "Offline radio signal analyzer."),
        ("kalibrate-rtl", "kal", "kalibrate-rtl", "Calibrate RTL-SDR against GSM."),
        ("multimon-ng", "multimon-ng", "multimon-ng", "Decode pager / digital radio."),
        ("rfcat", "rfcat", "rfcat", "Sub-GHz dongle console."),
        ("rfkill", "rfkill", "rfkill", "Enable/disable wireless radios."),
        ("gr-osmosdr", "osmocom_fft", "gr-osmosdr", "Osmocom SDR blocks / FFT."),
        ("uhd-host", "uhd_find_devices", "UHD", "USRP hardware driver tools."),
        ("apple-bleee", "bleah", "apple-bleee", "Apple BLE device research."),
        ("airodump-ng", "airodump-ng", "airodump-ng", "802.11 packet capture."),
        ("aireplay-ng", "aireplay-ng", "aireplay-ng", "802.11 injection and replay."),
        ("airmon-ng", "airmon-ng", "airmon-ng", "Enable monitor mode."),
        ("airbase-ng", "airbase-ng", "airbase-ng", "Software access point."),
        ("airdecap-ng", "airdecap-ng", "airdecap-ng", "Decrypt WEP/WPA capture files."),
        ("airtun-ng", "airtun-ng", "airtun-ng", "Virtual tunnel interface from 802.11."),
        ("packetforge-ng", "packetforge-ng", "packetforge-ng", "Craft 802.11 frames."),
        ("hcxpcapngtool", "hcxpcapngtool", "hcxpcapngtool", "Convert captures to hashcat/JTR."),
        ("hcxhashtool", "hcxhashtool", "hcxhashtool", "Work with PMKID/EAPOL hashes."),
        ("sakis3g", "sakis3g", "Sakis3G", "3G/UMTS modem helper."),
        ("hostapd-mana", "hostapd-mana", "hostapd-mana", "Rogue AP with MANA."),
        ("berate-ap", "berate-ap", "berate-ap", "Mana / rogue-AP wrapper."),
        ("pskracker", "pskracker", "PSKracker", "WPA PSK default-key generator."),
        ("proximoth", "proximoth", "Proximoth", "Wi-Fi proximity and presence."),
        ("gr-air-modes", "modes_rx", "gr-air-modes", "ADS-B / Mode S receiver."),
        ("vwifi-tool", "vwifi-tool", "vwifi-tool", "Virtual Wi-Fi helper."),
        ("wpa-sycophant", "wpa_sycophant", "WPA Sycophant", "Evil-twin EAP relay."),
        ("hak5-wifi-coconut", "wifi-coconut", "Hak5 WiFi Coconut", "Hak5 Coconut capture utility."),
        ("cupid-hostapd", "hostapd", "Cupid hostapd", "Cupid WPA3 hostapd build."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Reverse =
    [
        ("apktool", "apktool", "Apktool", "Decode and rebuild Android APKs."),
        ("bytecode-viewer", "bytecode-viewer", "Bytecode Viewer", "Java/Android reverse suite."),
        ("dex2jar", "d2j-dex2jar", "dex2jar", "Convert DEX to JAR."),
        ("edb-debugger", "edb", "edb", "AArch64/x86 debugger."),
        ("jadx", "jadx", "JADX", "Dex to Java decompiler."),
        ("javasnoop", "javasnoop", "JavaSnoop", "Hook Java method calls."),
        ("jd-gui", "jd-gui", "JD-GUI", "Java decompiler GUI."),
        ("ollydbg", "ollydbg", "OllyDbg", "32-bit Windows debugger (Wine)."),
        ("radare2", "r2", "radare2", "Reverse-engineering framework."),
        ("rizin", "rizin", "Rizin", "radare2 fork."),
        ("cutter", "cutter", "Cutter", "Rizin GUI."),
        ("ghidra", "ghidra", "Ghidra", "NSA SRE suite."),
        ("nasm", "nasm", "NASM", "Netwide assembler."),
        ("ropper", "ropper", "Ropper", "Find ROP gadgets."),
        ("detect-it-easy", "die", "Detect It Easy", "Packer / compiler identifier."),
        ("imhex", "imhex", "ImHex", "Hex editor for reverse engineers."),
        ("pyinstxtractor", "pyinstxtractor", "pyinstxtractor", "Extract PyInstaller binaries."),
        ("quark-engine", "quark", "Quark Engine", "Android malware scorer."),
        ("gdb", "gdb", "GDB", "GNU debugger."),
        ("gdb-peda", "gdb", "PEDA", "Python Exploit Development Assistance for GDB."),
        ("gef", "gdb", "GEF", "GDB Enhanced Features."),
        ("capstone-tool", "cstool", "Capstone", "Multi-arch disassembly."),
        ("clang", "clang", "Clang", "C/C++/ObjC compiler for rebuilds."),
        ("objdump", "objdump", "objdump", "Display object-file information."),
        ("readelf", "readelf", "readelf", "Display ELF headers and sections."),
        ("strings", "strings", "strings", "Extract printable strings from a binary."),
        ("nm", "nm", "nm", "List symbols from object files."),
        ("ltrace", "ltrace", "ltrace", "Library-call tracer."),
        ("strace", "strace", "strace", "System-call tracer."),
        ("hexedit", "hexedit", "hexedit", "ncurses hex editor."),
        ("xxd", "xxd", "xxd", "Hex dump and reverse."),
        ("iaito", "iaito", "iaito", "Official Rizin GUI."),
        ("hexwalk", "hexwalk", "HexWalk", "Hex editor for reverse engineers."),
        ("shed", "shed", "shed", "Simple hex editor with ASCII."),
        ("ruby-pedump", "pedump", "pedump", "Dump PE structure (Ruby)."),
        ("androguard", "androguard", "Androguard", "Android malware analysis."),
        ("smali", "smali", "smali", "Assemble Dalvik bytecode."),
        ("baksmali", "baksmali", "baksmali", "Disassemble DEX to smali."),
        ("checksec", "checksec", "checksec", "Check binary hardening flags."),
        ("ropgadget", "ROPgadget", "ROPgadget", "Search for ROP gadgets."),
        ("ghidra-headless", "analyzeHeadless", "Ghidra headless", "Ghidra analyzeHeadless."),
        ("pwndbg", "pwndbg", "pwndbg", "GDB plugin for exploit development."),
        ("rz-ghidra-re", "rz-ghidra", "rz-ghidra", "Ghidra decompiler plugin for Rizin."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Exploitation =
    [
        ("searchsploit", "searchsploit", "searchsploit", "Query Exploit-DB offline."),
        ("msfconsole", "msfconsole", "Metasploit", "Metasploit Framework console."),
        ("msfpc", "msfpc", "MSFvenom Payload Creator", "Quick msfvenom wrapper."),
        ("armitage", "armitage", "Armitage", "Metasploit GUI."),
        ("shellnoob", "shellnoob", "shellnoob", "Shellcode writing helper."),
        ("termineter", "termineter", "Termineter", "Smart-meter (C12.18) testing."),
        ("routersploit", "rsf.py", "RouterSploit", "Embedded-device exploitation."),
        ("pocsuite3", "pocsuite", "pocsuite3", "Remote vulnerability testing framework."),
        ("getsploit", "getsploit", "getsploit", "Search and download exploits."),
        ("linux-exploit-suggester", "linux-exploit-suggester.sh", "Linux Exploit Suggester", "Suggest kernel exploits from uname."),
        ("pompem", "pompem", "Pompem", "Exploit / tool search aggregator."),
        ("exploitdb", "searchsploit", "Exploit-DB", "Exploit-DB package (searchsploit)."),
        ("setoolkit", "setoolkit", "SET", "Social-Engineer Toolkit (also under SE)."),
        ("msfvenom", "msfvenom", "msfvenom", "Metasploit payload generator."),
        ("msfdb", "msfdb", "msfdb", "Metasploit database helper."),
        ("msfrpcd", "msfrpcd", "msfrpcd", "Metasploit RPC daemon."),
        ("starkiller", "starkiller", "Starkiller", "Metasploit GUI (Electron)."),
        ("unicorn-magic", "unicorn-magic", "Magic Unicorn", "PowerShell / HTA / macro payload generator."),
        ("shellfire", "shellfire", "shellfire", "Exploit development and payload helper."),
        ("windows-privesc-check", "windows-privesc-check", "windows-privesc-check", "Windows privilege-escalation auditor."),
        ("hyperion", "hyperion", "Hyperion", "AES crypter for PE payloads."),
        ("sharpshooter", "sharpshooter", "SharpShooter", "Payload generation framework."),
        ("donut", "donut", "Donut", "Position-independent shellcode from .NET assemblies."),
        ("framework2", "framework2", "Framework2", "Browser exploitation framework (legacy)."),
        ("teamsploit", "teamsploit", "TeamSploit", "Team-based exploitation helper."),
        ("payloadsallthethings", "payloadsallthethings", "PayloadsAllTheThings", "Payload collection package."),
        ("wesng", "wes", "WES-NG", "Windows Exploit Suggester Next Generation."),
        ("linux-exploit-suggester-2", "linux-exploit-suggester-2.sh", "Linux Exploit Suggester 2", "Suggest kernel exploits from uname."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Sniffing =
    [
        ("wireshark", "wireshark", "Wireshark", "GUI packet analyzer."),
        ("tshark", "tshark", "tshark", "Wireshark CLI."),
        ("tcpdump", "tcpdump", "tcpdump", "Classic packet capture."),
        ("bettercap", "bettercap", "bettercap", "MITM framework (net, wifi, BLE)."),
        ("ettercap", "ettercap", "Ettercap", "LAN MITM suite."),
        ("dsniff", "dsniff", "dsniff", "Password sniffing and spoofing suite."),
        ("responder", "responder", "Responder", "LLMNR/NBT-NS/MDNS poisoner."),
        ("mitmproxy", "mitmproxy", "mitmproxy", "Interactive HTTPS intercept proxy."),
        ("mitm6", "mitm6", "mitm6", "IPv6 WPAD spoofing for AD."),
        ("dnschef", "dnschef", "dnschef", "DNS proxy / cooker for MITM."),
        ("driftnet", "driftnet", "Driftnet", "Grab images from TCP streams."),
        ("darkstat", "darkstat", "darkstat", "Network traffic analyzer with graphs."),
        ("ferret-sidejack", "ferret", "Ferret", "SideJacking cookie capture."),
        ("hamster-sidejack", "hamster", "Hamster", "Replay captured cookies."),
        ("fiked", "fiked", "fiked", "Fake IKE daemon (VPN MITM)."),
        ("hexinject", "hexinject", "hexinject", "Hex packet injector / sniffer."),
        ("isr-evilgrade", "evilgrade", "Evilgrade", "Upgrade-path injection."),
        ("netsniff-ng", "netsniff-ng", "netsniff-ng", "High-performance sniffer toolkit."),
        ("rebind", "rebind", "rebind", "DNS rebinding helper."),
        ("sniffjoke", "sniffjoke", "SniffJoke", "Client-side TCP obfuscation vs IDS."),
        ("sslsniff", "sslsniff", "sslsniff", "MITM SSL/TLS downgrade."),
        ("sslsplit", "sslsplit", "sslsplit", "Transparent SSL/TLS intercept."),
        ("sslstrip", "sslstrip", "sslstrip", "HTTPS to HTTP stripping."),
        ("tcpflow", "tcpflow", "tcpflow", "Reconstruct TCP streams to files."),
        ("tcpreplay", "tcpreplay", "tcpreplay", "Replay pcap onto an interface."),
        ("above", "above", "above", "Network visibility / sniffing helper."),
        ("ngrep", "ngrep", "ngrep", "grep for the network."),
        ("netsed", "netsed", "netsed", "Alter network streams on the fly."),
        ("bruteshark", "brutesharkcli", "BruteShark", "Extract creds and hashes from pcap."),
        ("chaosreader", "chaosreader", "chaosreader", "Trace TCP/UDP sessions from pcap."),
        ("arpspoof", "arpspoof", "arpspoof", "ARP cache poisoning (dsniff)."),
        ("dnsspoof", "dnsspoof", "dnsspoof", "Forge DNS replies (dsniff)."),
        ("macof", "macof", "macof", "MAC flooding (dsniff)."),
        ("urlsnarf", "urlsnarf", "urlsnarf", "Sniff HTTP URLs (dsniff)."),
        ("msgsnarf", "msgsnarf", "msgsnarf", "Sniff chat messages (dsniff)."),
        ("filesnarf", "filesnarf", "filesnarf", "Sniff NFS files (dsniff)."),
        ("mailsnarf", "mailsnarf", "mailsnarf", "Sniff email on the wire (dsniff)."),
        ("sshmitm", "sshmitm", "sshmitm", "SSH man-in-the-middle (dsniff)."),
        ("webmitm", "webmitm", "webmitm", "HTTP/HTTPS MITM (dsniff)."),
        ("mitmdump", "mitmdump", "mitmdump", "mitmproxy non-interactive dump."),
        ("mitmweb", "mitmweb", "mitmweb", "mitmproxy web interface."),
        ("bettercap-ui", "bettercap-ui", "bettercap-ui", "bettercap web UI."),
        ("arpwatch", "arpwatch", "arpwatch", "Watch Ethernet for new MAC/IP pairs."),
        ("evil-ssdp", "evil-ssdp", "evil-ssdp", "Spoof SSDP / UPnP devices."),
        ("proxify", "proxify", "proxify", "Swiss-army proxy (ProjectDiscovery)."),
        ("portspoof", "portspoof", "portspoof", "Spoof all ports as open."),
        ("ifpps", "ifpps", "ifpps", "Top-like interface stats (netsniff-ng)."),
        ("trafgen", "trafgen", "trafgen", "Packet generator (netsniff-ng)."),
        ("flowtop", "flowtop", "flowtop", "Connection tracking top (netsniff-ng)."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] PostEx =
    [
        ("cymothoa", "cymothoa", "Cymothoa", "Inject a stealth backdoor into a process."),
        ("dbd", "dbd", "dbd", "Netcat-clone with encryption."),
        ("dns2tcp", "dns2tcp", "dns2tcp", "TCP over DNS tunnel."),
        ("exe2hexbat", "exe2hex", "exe2hex", "Convert binary to bat/hex for transfer."),
        ("iodine", "iodine", "iodine", "IP over DNS tunnel."),
        ("laudanum", "laudanum", "Laudanum", "Injectable web shells collection."),
        ("mimikatz", "mimikatz", "mimikatz", "Windows credential extraction (Wine/native)."),
        ("miredo", "miredo", "Miredo", "Teredo IPv6 tunnel."),
        ("nishang", "nishang", "Nishang", "PowerShell offensive framework (scripts)."),
        ("powersploit", "powersploit", "PowerSploit", "PowerShell post-ex modules."),
        ("proxychains4", "proxychains4", "proxychains4", "Force TCP through a proxy."),
        ("proxytunnel", "proxytunnel", "proxytunnel", "CONNECT-method HTTP(S) tunnel."),
        ("ptunnel", "ptunnel", "ptunnel", "TCP over ICMP."),
        ("pwnat", "pwnat", "pwnat", "NAT-to-NAT hole punch."),
        ("sbd", "sbd", "sbd", "Netcat-clone with encryption (Debian)."),
        ("shellter", "shellter", "Shellter", "Dynamic PE infector (AV bypass)."),
        ("stunnel4", "stunnel", "stunnel", "TLS wrap for arbitrary TCP."),
        ("udptunnel", "udptunnel", "udptunnel", "TCP over UDP tunnel."),
        ("veil", "veil", "Veil", "Payload generation framework."),
        ("webacoo", "webacoo", "WeBaCoo", "Web backdoor cookie-channel."),
        ("evil-winrm", "evil-winrm", "evil-winrm", "WinRM shell for pentests."),
        ("certipy-ad", "certipy", "Certipy", "AD CS enumeration and abuse."),
        ("bloodhound", "bloodhound", "BloodHound", "AD attack-path GUI."),
        ("bloodhound-ce-python", "bloodhound-ce-python", "BloodHound CE Python", "BloodHound CE ingestor."),
        ("sharphound", "SharpHound", "SharpHound", "BloodHound collector."),
        ("chisel", "chisel", "chisel", "Fast TCP/UDP tunnel over HTTP."),
        ("ligolo-ng", "ligolo-ng", "ligolo-ng", "TUN-based pivoting."),
        ("sliver", "sliver", "Sliver", "Adversary emulation / C2 (Kali package)."),
        ("empire", "empire", "PowerShell Empire", "PowerShell/Python post-ex (Kali package)."),
        ("impacket-secretsdump", "secretsdump.py", "impacket secretsdump", "DCSync / NTDS / SAM dump."),
        ("impacket-psexec", "psexec.py", "impacket psexec", "SMB remote exec."),
        ("impacket-wmiexec", "wmiexec.py", "impacket wmiexec", "WMI remote shell."),
        ("impacket-ntlmrelayx", "ntlmrelayx.py", "impacket ntlmrelayx", "NTLM relay."),
        ("pspy", "pspy", "pspy", "Unprivileged Linux process monitor."),
        ("koadic", "koadic", "Koadic", "COM-based Windows C2 (Kali package)."),
        ("pwncat", "pwncat-cs", "pwncat", "Netcat with persistence helpers."),
        ("villain", "villain", "Villain", "C2 / session handler (Kali package)."),
        ("hoaxshell", "hoaxshell", "HoaxShell", "Unconventional Windows reverse shell."),
        ("penelope", "penelope", "Penelope", "Shell handler."),
        ("krbrelayx", "krbrelayx", "krbrelayx", "Kerberos unconstrained-delegation abuse."),
        ("rubeus", "Rubeus", "Rubeus", "Kerberos abuse (Windows binary)."),
        ("hekatomb", "hekatomb", "Hekatomb", "Extract DCs and dump NTDS."),
        ("bloodyad", "bloodyAD", "bloodyAD", "Active Directory privilege escalation."),
        ("coercer", "coercer", "Coercer", "Coerce Windows authentication."),
        ("sprayhound", "sprayhound", "SprayHound", "Password spray using BloodHound data."),
        ("redsnarf", "redsnarf", "redsnarf", "Retrieve hashes and credentials remotely."),
        ("poshc2", "posh-server", "PoshC2", "Proxy-aware C2 (Kali package)."),
        ("havoc", "havoc", "Havoc", "C2 framework (Kali package)."),
        ("merlin-server", "merlin-server", "Merlin", "Cross-platform C2 (Kali package)."),
        ("silenttrinity", "st", "SILENTTRINITY", "IronPython C2 (Kali package)."),
        ("cryptcat", "cryptcat", "cryptcat", "Netcat with twofish encryption."),
        ("socat", "socat", "socat", "Multipurpose relay (TCP/UDP/SSL)."),
        ("netcat", "nc", "netcat", "TCP/UDP Swiss army knife."),
        ("powercat", "powercat", "powercat", "PowerShell netcat."),
        ("impacket-smbexec", "impacket-smbexec", "impacket smbexec", "SMB remote exec via services."),
        ("impacket-dcomexec", "impacket-dcomexec", "impacket dcomexec", "DCOM remote exec."),
        ("impacket-atexec", "impacket-atexec", "impacket atexec", "Task Scheduler remote exec."),
        ("impacket-smbclient", "impacket-smbclient", "impacket smbclient", "Impacket SMB client."),
        ("impacket-reg", "impacket-reg", "impacket reg", "Remote registry via Impacket."),
        ("impacket-rpcdump", "impacket-rpcdump", "impacket rpcdump", "Dump RPC endpoints."),
        ("dploot", "dploot", "dploot", "DPAPI loot remotely."),
        ("lapsdumper", "lapsdumper", "LAPSDumper", "Dump LAPS passwords."),
        ("ldeep", "ldeep", "ldeep", "LDAP enumeration."),
        ("certi", "certi", "certi", "AD CS enumeration."),
        ("sshuttle", "sshuttle", "sshuttle", "VPN over SSH."),
        ("ligolo-mp", "ligolo-mp", "ligolo-mp", "Ligolo multiplayer pivoting."),
        ("evil-winrm-py", "evil-winrm-py", "evil-winrm-py", "Python Evil-WinRM client."),
        ("hotpatch", "hotpatch", "hotpatch", "Hot-patch a running process."),
        ("tundeep", "tundeep", "tundeep", "TUN/TAP tunneling."),
        ("gsocket", "gsocket", "gsocket", "Global socket / firewall punch."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Forensics =
    [
        ("7z", "7z", "7-Zip", "Archive inspector."),
        ("affinfo", "affinfo", "AFFLib", "Advanced Forensic Format tools."),
        ("autopsy", "autopsy", "Autopsy", "Sleuth Kit GUI."),
        ("binwalk", "binwalk", "Binwalk", "Firmware / file-carve analyzer."),
        ("bulk-extractor", "bulk_extractor", "bulk_extractor", "Scan images for emails, CCNs, URLs."),
        ("cabextract", "cabextract", "cabextract", "Extract Microsoft CAB files."),
        ("chkrootkit", "chkrootkit", "chkrootkit", "Local rootkit detector."),
        ("dc3dd", "dc3dd", "dc3dd", "Patched dd with hashing for forensics."),
        ("dcfldd", "dcfldd", "dcfldd", "dd with hashing and split output."),
        ("ddrescue", "ddrescue", "ddrescue", "Data recovery from damaged media."),
        ("dumpzilla", "dumpzilla", "Dumpzilla", "Firefox/Thunderbird forensic dump."),
        ("ewfacquire", "ewfacquire", "libewf", "Expert Witness Format acquire."),
        ("exifprobe", "exifprobe", "exifprobe", "EXIF / TIFF probe."),
        ("exiv2", "exiv2", "Exiv2", "Image metadata read/write."),
        ("exiftool", "exiftool", "ExifTool", "Read metadata from almost any file."),
        ("ext3grep", "ext3grep", "ext3grep", "ext3 file undelete."),
        ("ext4magic", "ext4magic", "ext4magic", "ext3/ext4 recovery."),
        ("extundelete", "extundelete", "extundelete", "ext3/ext4 undelete."),
        ("firmware-mod-kit", "firmware-mod-kit", "Firmware Mod Kit", "Unpack and repack firmware."),
        ("foremost", "foremost", "foremost", "File carver by headers."),
        ("galleta", "galleta", "Galleta", "Parse IE cookies."),
        ("gpart", "gpart", "gpart", "Guess destroyed partition tables."),
        ("guymager", "guymager", "Guymager", "Forensic imager GUI."),
        ("hashdeep", "hashdeep", "hashdeep", "Recursive hash sets (also md5deep)."),
        ("inetsim", "inetsim", "INetSim", "Simulate common internet services in a lab."),
        ("mac-robber", "mac-robber", "mac-robber", "Collect MAC times for TSK."),
        ("magicrescue", "magicrescue", "Magic Rescue", "Carve files by magic bytes."),
        ("memdump", "memdump", "memdump", "Dump system memory."),
        ("metacam", "metacam", "MetaCam", "Digital-camera metadata."),
        ("missidentify", "missidentify", "Miss Identify", "Find Win32 apps hiding as another type."),
        ("myrescue", "myrescue", "myrescue", "Rescue still-readable data from a disk."),
        ("nasty", "nasty", "nasty", "Recover a GPG passphrase from an agent."),
        ("pasco", "pasco", "pasco", "Parse IE index.dat."),
        ("pdf-parser", "pdf-parser", "pdf-parser", "Parse PDF structure."),
        ("pdfid", "pdfid", "pdfid", "Scan PDFs for active content."),
        ("plaso", "log2timeline.py", "Plaso", "Super timeline creation."),
        ("readpe", "readpe", "readpe", "Inspect PE files."),
        ("recoverdm", "recoverdm", "recoverdm", "Recover from damaged CD/DVD/disk."),
        ("recoverjpeg", "recoverjpeg", "recoverjpeg", "Carve JPEGs from a block device."),
        ("reglookup", "reglookup", "reglookup", "Read Windows registry hives."),
        ("regripper", "rip.pl", "RegRipper", "Extract keys from Windows registry."),
        ("rifiuti", "rifiuti", "rifiuti", "Parse INFO2 recycle bin."),
        ("rifiuti2", "rifiuti2", "rifiuti2", "Recycle-bin parser (updated)."),
        ("rkhunter", "rkhunter", "rkhunter", "Rootkit hunter."),
        ("rsakeyfind", "rsakeyfind", "rsakeyfind", "Find BER-encoded RSA keys in a dump."),
        ("safecopy", "safecopy", "safecopy", "Robust file copy past read errors."),
        ("scalpel", "scalpel", "Scalpel", "Fast file carver."),
        ("scrounge-ntfs", "scrounge-ntfs", "scrounge-ntfs", "Carve files from NTFS."),
        ("fls", "fls", "Sleuth Kit fls", "List files in a disk image."),
        ("tsk-icat", "icat", "Sleuth Kit icat", "Output a file by inode."),
        ("ssdeep", "ssdeep", "ssdeep", "Context-triggered piecewise hashes."),
        ("tcpick", "tcpick", "tcpick", "TCP stream sniffer and tracker."),
        ("undbx", "undbx", "undbx", "Extract Outlook Express DBX."),
        ("unhide", "unhide", "unhide", "Find hidden processes and ports."),
        ("upx", "upx", "UPX", "Pack / unpack executables."),
        ("vinetto", "vinetto", "Vinetto", "Examine Thumbs.db."),
        ("wce", "wce", "WCE", "Windows Credentials Editor."),
        ("xmount", "xmount", "xmount", "Convert on-the-fly between disk-image formats."),
        ("xplico", "xplico", "Xplico", "Network forensic analysis (NFAT)."),
        ("yara", "yara", "YARA", "Malware pattern matching."),
        ("testdisk", "testdisk", "TestDisk", "Partition recovery."),
        ("photorec", "photorec", "PhotoRec", "Carve photos and documents."),
        ("volatility3", "vol", "Volatility 3", "Memory forensics."),
        ("chainsaw", "chainsaw", "Chainsaw", "Hunt EVTX and other logs."),
        ("oletools", "olevba", "oletools", "Analyze MS Office / OLE macros."),
        ("hashrat", "hashrat", "Hashrat", "Recursive hashing."),
        ("aeskeyfind", "aeskeyfind", "aeskeyfind", "Find AES keys in a memory dump."),
        ("aesfix", "aesfix", "aesfix", "Correct bit errors in AES-128 keys."),
        ("steghide", "steghide", "steghide", "Hide / extract data in images or audio."),
        ("stegosuite", "stegosuite", "Stegosuite", "Steganography GUI."),
        ("stegsnow", "stegsnow", "stegsnow", "Whitespace steganography."),
        ("stegcracker", "stegcracker", "StegCracker", "Steghide brute force."),
        ("ccrypt", "ccrypt", "ccrypt", "Encrypt / decrypt files."),
        ("unblob", "unblob", "unblob", "Extract files from any blob / firmware."),
        ("readpst", "readpst", "readpst", "Convert Outlook PST to mbox."),
        ("hivex", "hivexget", "hivex", "Read Windows registry hives."),
        ("binwalk3-for", "binwalk3", "Binwalk 3 (forensics)", "Firmware and blob extraction."),
        ("forensic-artifacts", "forensic-artifacts", "forensic-artifacts", "Forensic artifact definitions."),
        ("forensics-colorize", "filecompare", "forensics-colorize", "Colorize binary differences."),
        ("grokevt", "grokevt-parselog", "grokevt", "Parse Windows Event Logs."),
        ("md5deep", "md5deep", "md5deep", "Recursive MD5 (hashdeep suite)."),
        ("rephrase", "rephrase", "rephrase", "Passphrase recovery helper."),
        ("unrar", "unrar", "unrar", "Extract RAR archives."),
        ("ewfinfo", "ewfinfo", "ewfinfo", "Show EWF/E01 image info."),
        ("ewfexport", "ewfexport", "ewfexport", "Export from EWF images."),
        ("ewfverify", "ewfverify", "ewfverify", "Verify EWF image integrity."),
        ("tsk-ils", "ils", "Sleuth Kit ils", "List inodes in an image."),
        ("tsk-istat", "istat", "Sleuth Kit istat", "Inode details."),
        ("tsk-mmls", "mmls", "Sleuth Kit mmls", "Display partition layout."),
        ("tsk-fsstat", "fsstat", "Sleuth Kit fsstat", "File-system statistics."),
        ("tsk-ffind", "ffind", "Sleuth Kit ffind", "Find file by metadata address."),
        ("tsk-ifind", "ifind", "Sleuth Kit ifind", "Find inode by data unit or name."),
        ("tsk-blkcat", "blkcat", "Sleuth Kit blkcat", "Output a data unit."),
        ("tsk-blkls", "blkls", "Sleuth Kit blkls", "List unallocated blocks."),
        ("tsk-mactime", "mactime", "Sleuth Kit mactime", "Create a MAC timeline."),
        ("tsk-recover", "tsk_recover", "Sleuth Kit recover", "Recover files from an image."),
        ("fatcat", "fatcat", "fatcat", "Explore and recover FAT filesystems."),
        ("dislocker", "dislocker", "dislocker", "Read BitLocker volumes."),
        ("exiflooter", "exiflooter", "exiflooter", "EXIF OSINT from images."),
        ("gtkhash", "gtkhash", "GtkHash", "GUI checksum calculator."),
        ("sigma-cli", "sigma", "sigma-cli", "Convert Sigma detection rules."),
        ("snowdrop", "snowdrop", "snowdrop", "Watermark and stego text."),
        ("unhide-rb", "unhide.rb", "unhide.rb", "Find hidden processes (Ruby)."),
        ("dwarf2json", "dwarf2json", "dwarf2json", "Build Volatility ISF from DWARF."),
        ("affcat", "affcat", "affcat", "Output AFF image contents."),
        ("affconvert", "affconvert", "affconvert", "Convert to or from AFF."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Reporting =
    [
        ("cutycapt", "cutycapt", "CutyCapt", "WebKit screenshot to image/vector."),
        ("dradis", "dradis", "Dradis", "Collaboration and reporting framework."),
        ("eyewitness", "eyewitness", "EyeWitness", "Screenshot and header capture for URLs."),
        ("faraday", "faraday", "Faraday", "IPM / collaborative pentest IDE."),
        ("recordmydesktop", "recordmydesktop", "recordMyDesktop", "Session video capture."),
        ("gowitness", "gowitness", "gowitness", "Web screenshot using Chrome Headless."),
        ("faraday-cli", "faraday-cli", "faraday-cli", "Faraday from the command line."),
        ("metagoofil-report", "metagoofil", "metagoofil (report)", "Document metadata for the report annex."),
        ("defectdojo", "defectdojo", "DefectDojo", "DevSecOps vulnerability management."),
        ("joplin", "joplin", "Joplin", "Note-taking for engagement notes."),
        ("obsidian", "obsidian", "Obsidian", "Markdown knowledge base."),
        ("cherrytree", "cherrytree", "CherryTree", "Hierarchical note-taking."),
        ("zim", "zim", "Zim", "Desktop wiki for notes."),
        ("faraday-agent-dispatcher", "faraday-agent-dispatcher", "Faraday dispatcher", "Faraday agent dispatcher."),
        ("witnessme", "witnessme", "WitnessMe", "Web inventory screenshotter."),
        ("arsenal-ng", "arsenal", "Arsenal", "Cheatsheet launcher for pentest commands."),
        ("maltego-report", "maltego", "Maltego (report)", "Link-analysis graphs for the report."),
        ("pipal-report", "pipal", "pipal (report)", "Password-list statistics for the annex."),
        ("casefile", "casefile", "CaseFile", "Maltego CaseFile (offline graphs)."),
        ("magictree", "magictree", "MagicTree", "Data collection and reporting (if packaged)."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Social =
    [
        ("beef-xss", "beef", "BeEF", "Browser Exploitation Framework."),
        ("set-se", "setoolkit", "Social-Engineer Toolkit", "Phishing, payloads, and SE attacks."),
        ("msfpc-se", "msfpc", "MSFPC (SE)", "Quick payload generator for client-side tests."),
        ("veil-se", "veil", "Veil (SE)", "Payload generation for SE engagements."),
        ("gophish", "gophish", "Gophish", "Phishing-campaign framework."),
        ("evilginx2", "evilginx", "Evilginx2", "Phishlet MITM for MFA-aware campaigns."),
        ("maltego-se", "maltego", "Maltego (SE)", "People / org link analysis."),
        ("wifiphisher-se", "wifiphisher", "Wifiphisher (SE)", "Rogue-AP credential harvest."),
        ("king-phisher", "king-phisher", "King Phisher", "Phishing campaign toolkit (if packaged)."),
        ("phishery", "phishery", "Phishery", "Basic Auth credential harvester via .docx."),
        ("linkedin2username", "linkedin2username", "linkedin2username", "Generate username lists from LinkedIn."),
        ("email2phonenumber", "email2phonenumber", "email2phonenumber", "OSINT email-to-phone correlation."),
        ("instaloader", "instaloader", "Instaloader", "Download Instagram profiles and posts."),
        ("inspy", "inspy", "InSpy", "LinkedIn enumeration."),
        ("wotmate", "wotmate", "WOTmate", "Web-of-trust / identity OSINT."),
        ("hb-honeypot", "hb-honeypot", "HB honeypot", "Honeybadger-style honeypot helper."),
        ("websploit", "websploit", "Websploit", "Web/MITM social-engineering toolkit."),
        ("cupp", "cupp", "CUPP", "Common User Passwords Profiler."),
        ("fluxion-se", "fluxion", "Fluxion (SE)", "WPA captive-portal social engineering."),
        ("unicorn-se", "unicorn-magic", "Magic Unicorn (SE)", "Client-side payload generator."),
        ("set-cli", "setoolkit", "setoolkit (SE CLI)", "Social-Engineer Toolkit launcher."),
    ];

    private static readonly (string Id, string Exe, string Name, string Summary)[] Hardware =
    [
        ("binwalk-hw", "binwalk", "Binwalk (hardware)", "Firmware extraction for device work."),
        ("cutecom", "cutecom", "CuteCom", "Graphical serial terminal."),
        ("flashrom", "flashrom", "flashrom", "Read/write firmware flash chips."),
        ("minicom", "minicom", "minicom", "Serial console."),
        ("openocd", "openocd", "OpenOCD", "On-chip debug (JTAG/SWD)."),
        ("qemu-system-x86", "qemu-system-x86_64", "QEMU", "Emulate firmware and devices."),
        ("qemu-user", "qemu-x86_64", "QEMU user", "User-mode emulation."),
        ("proxmark3-hw", "pm3", "Proxmark3 (HW)", "RFID lab workbench."),
        ("rfdump-hw", "rfdump", "RFDump (HW)", "RFID tag dump."),
        ("hackrf-hw", "hackrf_transfer", "HackRF transfer", "Record / replay RF."),
        ("openocd-hw", "openocd", "OpenOCD scripts", "Board config + GDB server."),
        ("binwalk3", "binwalk3", "Binwalk 3", "Next-gen firmware extraction."),
        ("radare2-hw", "r2", "radare2 (hardware)", "Disassemble firmware dumps."),
        ("cutter-hw", "cutter", "Cutter (hardware)", "Rizin GUI for firmware."),
        ("rz-ghidra", "rz-ghidra", "rz-ghidra", "Ghidra decompiler plugin for Rizin."),
        ("android-sdk", "adb", "Android SDK / adb", "Android Debug Bridge."),
        ("google-nexus-tools", "fastboot", "Nexus tools / fastboot", "Fastboot for Android devices."),
        ("i2cdetect", "i2cdetect", "i2cdetect", "Scan I2C buses (i2c-tools)."),
        ("picocom", "picocom", "picocom", "Minimal serial terminal."),
        ("avrdude", "avrdude", "avrdude", "AVR microcontroller programmer."),
        ("dfu-util", "dfu-util", "dfu-util", "Device Firmware Upgrade utility."),
        ("pulseview", "pulseview", "PulseView", "sigrok logic-analyzer GUI."),
        ("sigrok-cli", "sigrok-cli", "sigrok-cli", "sigrok command-line frontend."),
        ("esptool", "esptool", "esptool", "Espressif ROM bootloader utility."),
        ("nfc-list", "nfc-list", "nfc-list", "List NFC devices and tags (libnfc)."),
        ("mfoc", "mfoc", "MFOC", "MIFARE Classic offline cracker."),
        ("mfcuk", "mfcuk", "MFCUK", "MIFARE Classic Darkside attack."),
        ("qemu-system-arm", "qemu-system-arm", "QEMU ARM", "Emulate ARM firmware."),
        ("qemu-system-mips", "qemu-system-mips", "QEMU MIPS", "Emulate MIPS firmware."),
        ("qemu-system-aarch64", "qemu-system-aarch64", "QEMU AArch64", "Emulate AArch64 firmware."),
    ];
}
